name: my workflow
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Log level'     
        required: true
        default: 'main'
      repo:
        description: 'repository where code is residing'
        required: true
        default: 'test'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set branch
      run: echo "BRANCH=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
    - name: Set Repo
      run : echo "REPO=${{ github.event.inputs.repo_name }}" >> $GITHUB_ENV
    - name: Test
      run: echo $BRANCH $REPO
