name: my workflow
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'     
        required: true
        default: 'main'
      repo:
        description: 'repository where code is residing'
        required: true
        default: 'test'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set branch
      run: echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
    - name: Set Repo
      run : echo "REPO=${{ github.event.inputs.repo }}" >> $GITHUB_ENV
    - name: Test
      run: echo $BRANCH $REPO
    - name: Validate Input
      if: "${{ github.event.inputs.repo != '' }}" 
      run: |
        $result= git ls-remote --heads https://github.com/${{ github.event.inputs.repo }}/${{ github.event.inputs.repo }}.git
        echo $result
    - name: Validate Input
      if: "${{ github.event.inputs.branch != '' }}" 
      run: |
       $result= git ls-remote --heads https://github.com/${{ github.event.inputs.repo }}/${{ github.event.inputs.repo }}.git ${{ github.event.inputs.branch }}
       echo $result
